name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  fl_chart: ^0.69.0
  tutorial_coach_mark: ^1.2.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # ▼▼ ガチャ用の画像フォルダを追加 ▼▼
    - assets/images/gacha/
    # ▼▼ マスタデータ用のJSONフォルダを追加 ▼▼
    - assets/json/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  # Androidのアダプティブアイコン用背景色（必要なら）
  # adaptive_icon_background: "#FFFFFF" 
  # Androidのアダプティブアイコン用前面画像（必要なら指定。なければimage_pathが使われる）
  # adaptive_icon_foreground: "assets/icon/app_icon.png"