name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 日本語化パッケージ
  flutter_localizations:
    sdk: flutter
    
  # 日付操作
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ▼▼ 正しい位置はここ（flutterセクションの中）です ▼▼
  assets:
    - assets/images/